config/routes.rb
Rails.application.routes.draw do

  get 'battery_charges/new'

  get 'battery_charges/create'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  
  resources :users
  resources :load_states, only: [:new, :show, :create]
  resources :battery_charges, only: [:new, :create]

  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get 'newLoad'     => 'users#newLoad'
  post 'createLoad' => 'users#createLoad'
  get 'profile'     => 'users#profile'
  
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.new
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Alternative Energy Solution</h1>

<div id = "login">
    <h2> Login </h2>
    
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_for(:session, url: login_path) do |f| %>
    
	            <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>

                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
        
		        <%= f.submit "Log in", class: "btn btn-primary" %>
	        <% end %>
	    </div>
    </div>
</div>

<div id = "signup">
    <h2> Sign Up!</h2>
    
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_for(@user) do |f| %>

              <%= render 'shared/error_messages', object: f.object %>
                
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>

              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control' %>

              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>

              <%= f.label :password_confirmation, "Confirmation" %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>

              <%= f.submit "Create my account", class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
</div>
<div style="clear: both;"></div>