config/routes.rb
Rails.application.routes.draw do

  get 'battery_charges/new'

  get 'battery_charges/create'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  
  resources :users
  resources :load_states, only: [:new, :show, :create]
  resources :battery_charges, only: [:new, :create]

  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get 'newLoad'     => 'users#newLoad'
  post 'createLoad' => 'users#createLoad'
  get 'profile'     => 'users#profile'
  
 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small id = "footer1">
      Trine University ECE - Senior Design   
  </small>
  <small id ="footer2">
  Daniel Burns, Tony Huerta, Michael Stabler, Taylor Wisler, Andrew Wong
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Smart Power", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
	      <li><%= link_to "Profile", current_user %></li>
	      <li><%= link_to "New Load", new_load_state_path %></li>
	      <li><%= link_to "New Charge", new_battery_charge_path %></li>
	      <li><%= link_to "Settings", '#' %></li>
	      <li><%= link_to "Logout", logout_path, method: "delete"  %></li>
	      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>